### This is the Terraform-generated dev-build.yml workflow for the          ###
### docker-matomo-dev app repository.                                       ###
name: Dev Container Build and Deploy

# checkov:skip=CKV2_GHA_1:The shared workflow contains the permissions constraints
# NOTE: The above checkov skip command doesn't actually work and this workflow
#       will always show a checkov warning.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Dev Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-dev.yml@INFRA-526
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "docker-matomo-gha-dev"
      ECR: "docker-matomo-dev"
