### This is the Terraform-generated dev-build.yml workflow for the          ###
### docker-matomo-stage app repository.                                     ###
name: Stage Build and Push ECR Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    name: Stage Build and Push Image
    uses: mitlibraries/.github/.github/workflows/ecr-multi-arch-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "docker-matomo-gha-stage"
      ECR: "docker-matomo-stage"
      # DOCKERFILE: # only if the name of the Dockerfile is not "Dockerfile"!
      # FUNCTION: "" # only if this is a container-based Lambda function
      # PREBUILD:  # only if there is some pre-build dependency 
